name: CI

on:
  pull_request:
  push:
    tags:
      - 'v*'
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - run: cargo clippy --workspace --all-targets --all-features -- --deny warnings --allow unknown_lints
      - run: cargo fmt --all --check

  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}


      - run: cargo test --workspace --all-targets --all-features

  cross-build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    env:
      # see https://woodruffw.github.io/zizmor/audits/#template-injection
      REF_NAME: ${{ github.ref_name }}
      # renovate: datasource=crate depName=cross versioning=semver
      CROSS_VERSION: 0.2.5
      TARGET_ARCH: aarch64-unknown-linux-gnu
      RUSTFLAGS: "-D warnings"

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - run: cargo install cross --vers ${CROSS_VERSION}
      - run: cross build --release --target=${TARGET_ARCH}

      - run: cp target/${TARGET_ARCH}/release/clubfridge-neo clubfridge-neo
        if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'

      - run: tar czf clubfridge-neo-${REF_NAME}-${TARGET_ARCH}.tar.gz clubfridge-neo
        if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'
        with:
          name: clubfridge-neo-${{ env.REF_NAME }}-${{ env.TARGET_ARCH }}.tar.gz
          path: clubfridge-neo-${{ env.REF_NAME }}-${{ env.TARGET_ARCH }}.tar.gz

      - uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: clubfridge-neo-${{ env.REF_NAME }}-${{ env.TARGET_ARCH }}.tar.gz
